/**
 * Error codes.
 *
 * Stable machine-readable strings shared by the API and every frontend, so a client
 * can switch on the code instead of matching a localized message. Adding a code here
 * and using it is the only supported way to return an error.
 */

export const ErrorCode = {
  // generic
  INTERNAL: 'INTERNAL',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  STALE_WRITE: 'STALE_WRITE',

  // auth
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  // tenancy & access
  FORBIDDEN: 'FORBIDDEN',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  MISSING_TENANT_CONTEXT: 'MISSING_TENANT_CONTEXT',
  CROSS_TENANT_ACCESS: 'CROSS_TENANT_ACCESS',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  MODULE_DISABLED: 'MODULE_DISABLED',
  MODULE_DEPENDENCY_MISSING: 'MODULE_DEPENDENCY_MISSING',
  MODULE_HAS_DEPENDENTS: 'MODULE_HAS_DEPENDENTS',
  MODULE_IS_CORE: 'MODULE_IS_CORE',
  MODULE_NOT_AVAILABLE: 'MODULE_NOT_AVAILABLE',
  UPGRADE_REQUIRED: 'UPGRADE_REQUIRED',
  LAST_OWNER: 'LAST_OWNER',

  // catalog & inventory
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  MODIFIER_SELECTION_INVALID: 'MODIFIER_SELECTION_INVALID',

  // cart & orders
  CART_EMPTY: 'CART_EMPTY',
  ORDER_NOT_MODIFIABLE: 'ORDER_NOT_MODIFIABLE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  MINIMUM_ORDER_NOT_MET: 'MINIMUM_ORDER_NOT_MET',
  DELIVERY_ZONE_UNSUPPORTED: 'DELIVERY_ZONE_UNSUPPORTED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // promotions & loyalty
  PROMO_NOT_FOUND: 'PROMO_NOT_FOUND',
  PROMO_EXPIRED: 'PROMO_EXPIRED',
  PROMO_USAGE_EXCEEDED: 'PROMO_USAGE_EXCEEDED',
  PROMO_NOT_APPLICABLE: 'PROMO_NOT_APPLICABLE',
  INSUFFICIENT_LOYALTY_BALANCE: 'INSUFFICIENT_LOYALTY_BALANCE',

  // booking
  BOOKING_SLOT_TAKEN: 'BOOKING_SLOT_TAKEN',
  BOOKING_OUTSIDE_WORKING_HOURS: 'BOOKING_OUTSIDE_WORKING_HOURS',
  BOOKING_TOO_SOON: 'BOOKING_TOO_SOON',
  BOOKING_TOO_FAR: 'BOOKING_TOO_FAR',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',
  RESOURCE_UNAVAILABLE: 'RESOURCE_UNAVAILABLE',

  // payments
  PAYMENT_PROVIDER_UNAVAILABLE: 'PAYMENT_PROVIDER_UNAVAILABLE',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_ALREADY_FINALIZED: 'PAYMENT_ALREADY_FINALIZED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // telegram
  TELEGRAM_SIGNATURE_INVALID: 'TELEGRAM_SIGNATURE_INVALID',
  TELEGRAM_INITDATA_EXPIRED: 'TELEGRAM_INITDATA_EXPIRED',
  TELEGRAM_BOT_TOKEN_INVALID: 'TELEGRAM_BOT_TOKEN_INVALID',
  TELEGRAM_BOT_ALREADY_CONNECTED: 'TELEGRAM_BOT_ALREADY_CONNECTED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Default HTTP status per code — the exception filter uses this. */
export const ERROR_HTTP_STATUS: Record<ErrorCodeValue, number> = {
  INTERNAL: 500,
  VALIDATION_FAILED: 422,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  STALE_WRITE: 409,

  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  REFRESH_TOKEN_REUSED: 401,
  EMAIL_ALREADY_REGISTERED: 409,
  ACCOUNT_LOCKED: 423,

  FORBIDDEN: 403,
  NOT_A_MEMBER: 403,
  MISSING_TENANT_CONTEXT: 500,
  CROSS_TENANT_ACCESS: 403,
  TENANT_SUSPENDED: 403,
  MODULE_DISABLED: 403,
  MODULE_DEPENDENCY_MISSING: 422,
  MODULE_HAS_DEPENDENTS: 409,
  MODULE_IS_CORE: 409,
  MODULE_NOT_AVAILABLE: 409,
  UPGRADE_REQUIRED: 402,
  LAST_OWNER: 409,

  PRODUCT_UNAVAILABLE: 409,
  INSUFFICIENT_STOCK: 409,
  MODIFIER_SELECTION_INVALID: 422,

  CART_EMPTY: 409,
  ORDER_NOT_MODIFIABLE: 409,
  INVALID_STATUS_TRANSITION: 409,
  MINIMUM_ORDER_NOT_MET: 422,
  DELIVERY_ZONE_UNSUPPORTED: 422,
  IDEMPOTENCY_KEY_REUSED: 409,

  PROMO_NOT_FOUND: 404,
  PROMO_EXPIRED: 409,
  PROMO_USAGE_EXCEEDED: 409,
  PROMO_NOT_APPLICABLE: 422,
  INSUFFICIENT_LOYALTY_BALANCE: 409,

  BOOKING_SLOT_TAKEN: 409,
  BOOKING_OUTSIDE_WORKING_HOURS: 422,
  BOOKING_TOO_SOON: 422,
  BOOKING_TOO_FAR: 422,
  BOOKING_NOT_CANCELLABLE: 409,
  RESOURCE_UNAVAILABLE: 409,

  PAYMENT_PROVIDER_UNAVAILABLE: 503,
  PAYMENT_AMOUNT_MISMATCH: 409,
  PAYMENT_ALREADY_FINALIZED: 409,
  PAYMENT_NOT_FOUND: 404,
  PAYMENT_FAILED: 402,
  WEBHOOK_SIGNATURE_INVALID: 401,

  TELEGRAM_SIGNATURE_INVALID: 401,
  TELEGRAM_INITDATA_EXPIRED: 401,
  TELEGRAM_BOT_TOKEN_INVALID: 422,
  TELEGRAM_BOT_ALREADY_CONNECTED: 409,
};

/**
 * The only error type domain services should throw.
 *
 * Domain code must not import HTTP exceptions — that would couple business rules to a
 * transport. The API's exception filter maps DomainError to a response; a CLI, a worker
 * or a future gRPC surface maps it differently.
 */
export class DomainError extends Error {
  constructor(
    readonly code: ErrorCodeValue,
    message?: string,
    readonly details?: Record<string, unknown>,
  ) {
    super(message ?? code);
    this.name = 'DomainError';
  }

  get httpStatus(): number {
    return ERROR_HTTP_STATUS[this.code] ?? 500;
  }
}

export const notFound = (entity: string, id?: string) =>
  new DomainError(ErrorCode.NOT_FOUND, `${entity} not found`, id ? { entity, id } : { entity });

export const forbidden = (reason: string, details?: Record<string, unknown>) =>
  new DomainError(ErrorCode.FORBIDDEN, reason, details);
