/**
 * Server-only helpers.
 *
 * Imported as `@bizbot/shared/server`. Kept out of the root entry so the admin and Mini
 * App bundles never pull node:crypto into the browser.
 */

import { randomBytes, randomUUID } from 'node:crypto';

/** Primary keys are UUID v4 — generated by the app so relations can be built before write. */
export const newId = (): string => randomUUID();

const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'; // Crockford base32: no I, L, O, U

/**
 * Human-facing codes: order numbers, promo codes, referral codes.
 * Crockford's alphabet avoids characters a customer reads back wrong over the phone.
 */
export function randomCode(length = 8): string {
  const bytes = randomBytes(length);
  let out = '';
  for (let i = 0; i < length; i++) {
    out += ALPHABET[(bytes[i] ?? 0) % ALPHABET.length];
  }
  return out;
}

/** URL-safe secret, e.g. a Telegram webhook path segment. */
export function randomSecret(bytes = 32): string {
  return randomBytes(bytes).toString('base64url');
}
